// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiCjQeFKUn6aVP4F1XrOgzFo548blu914',
    appId: '1:870640294623:web:773360911102c9505b276a',
    messagingSenderId: '870640294623',
    projectId: 'artgram-e4223',
    authDomain: 'artgram-e4223.firebaseapp.com',
    storageBucket: 'artgram-e4223.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNaunoPnkUe-125SXPbn4bIu8O-hSpZM0',
    appId: '1:870640294623:android:bf4dd4d3cdd2ca5e5b276a',
    messagingSenderId: '870640294623',
    projectId: 'artgram-e4223',
    storageBucket: 'artgram-e4223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcnbYmi3LkuqxjRjaN1_oCkVXzct4I9ds',
    appId: '1:870640294623:ios:0cb1b31ebfbe62575b276a',
    messagingSenderId: '870640294623',
    projectId: 'artgram-e4223',
    storageBucket: 'artgram-e4223.firebasestorage.app',
    iosBundleId: 'com.example.artgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcnbYmi3LkuqxjRjaN1_oCkVXzct4I9ds',
    appId: '1:870640294623:ios:0cb1b31ebfbe62575b276a',
    messagingSenderId: '870640294623',
    projectId: 'artgram-e4223',
    storageBucket: 'artgram-e4223.firebasestorage.app',
    iosBundleId: 'com.example.artgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiCjQeFKUn6aVP4F1XrOgzFo548blu914',
    appId: '1:870640294623:web:c726b37cf58ad4d25b276a',
    messagingSenderId: '870640294623',
    projectId: 'artgram-e4223',
    authDomain: 'artgram-e4223.firebaseapp.com',
    storageBucket: 'artgram-e4223.firebasestorage.app',
  );
}
